#
# Created by JFormDesigner on Fri Mar 15 12:50:40 CST 2024
#
VerificationPanel.termsLabel.text=Terms of Service
VerificationPanel.registerLabel.text=Register
VerificationPanel.passwordLabel.text=password
VerificationPanel.privacyLabel.text=Privacy Policy
VerificationPanel.loginButton.text=Login
VerificationPanel.usernameLabel.text=username
VerificationPanel.login.exception=JVM Occurs a Error
